policy_path: checkpoints/tracking.onnx
motion_path: ../datasets/motions/vita_boy/dance.npz
motion_torso_index: 9
action_scale: 0.25

default_angles: [-0.312,  -0.312,   0.0,
                  0.0,     0.0,     0.0,
                  0.0,     0.0,     0.0,
                  0.669,   0.669,           0.2,   0.2,
                 -0.363,  -0.363,           0.2,  -0.2,
                  0.0,     0.0,             0.0,   0.0,
                                            0.6,   0.6,
                                            0.0,   0.0,
                                            0.0,   0.0,
                                            0.0,   0.0]

kps: [200, 200, 200,
      150, 150, 30,
      100, 100, 30,
      150, 150,     15, 15,
      30,  30,      15, 15,
      30,  30,      15, 15,
                    15, 15,
                    15, 15,
                    10, 10,
                    10, 10]

kds: [5, 5, 5,
      4, 4, 2,
      3, 3, 2,
      4, 4,     1, 1,
      2, 2,     1, 1,
      2, 2,     1, 1,
                1, 1,
                1, 1,
                1, 1,
                1, 1]

effort_limit: [150, 150, 150,
               139, 139, 60,
               88,  88,  60,
               139, 139,     30, 30,
               60,  60,      30, 30,
               60,  60,      30, 30,
                             30, 30,
                             30, 30,
                             7,  7,
                             7,  7]

joint2motor_idx: [0, 6, 12,
                  1, 7, 13,
                  2, 8, 14,
                  3, 9,     15, 22,
                  4, 10,    16, 23,
                  5, 11,    17, 24,
                            18, 25,
                            19, 26,
                            20, 27,
                            21, 28]
